package com.example.depttree;

import java.util.Arrays;

import org.apache.logging.log4j.LogManager;
import org.apache.logging.log4j.Logger;

import com.example.depttree.logic.DeptTreeApplication;

/**
 * Generated by GitHub Copilot (GPT-5.4)
 */
public class Main {

	private static final Logger LOGGER = LogManager.getLogger(Main.class);

	/**
	 * アプリケーションを起動します。
	 *
	 * @param args CLI引数
	 */
	public static void main(final String[] args) {
		final long startedAt = System.nanoTime();
		LOGGER.info("main started. args={}", Arrays.toString(args));
		int exitCode = 1;
		try {
			exitCode = new DeptTreeApplication().run(args);
		} catch (final RuntimeException exception) {
			LOGGER.error("Unexpected error occurred.", exception);
		} finally {
			final long elapsedMillis = (System.nanoTime() - startedAt) / 1_000_000L;
			LOGGER.info("main finished. exitCode={}, elapsedMillis={}", exitCode, elapsedMillis);
		}
		if (exitCode != 0) {
			System.exit(exitCode);
		}
	}
}