package com.example.depttree;

import com.example.depttree.logic.DeptTreeApplication;
import java.util.Arrays;
import org.apache.logging.log4j.LogManager;
import org.apache.logging.log4j.Logger;

/**
 * Generated by GitHub Copilot (GPT-5.3-Codex)
 */
public class Main {

    private static final Logger LOGGER = LogManager.getLogger(Main.class);

    /**
     * プログラムのエントリーポイント。
     *
     * @param args コマンドライン引数
     */
    public static void main(String[] args) {
        long startNanos = System.nanoTime();
        LOGGER.info("Main.main start args={}", Arrays.toString(args));

        int exitCode = new DeptTreeApplication().run(args);

        long elapsedMs = (System.nanoTime() - startNanos) / 1_000_000L;
        LOGGER.info("Main.main end elapsedMs={} exitCode={}", Long.valueOf(elapsedMs), Integer.valueOf(exitCode));
        if (exitCode != 0) {
            System.exit(exitCode);
        }
    }
}
