package com.example.depttree.logic;

import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.Paths;
import java.util.ArrayList;
import java.util.LinkedHashSet;
import java.util.List;
import java.util.regex.Pattern;

import org.apache.logging.log4j.LogManager;
import org.apache.logging.log4j.Logger;

/**
 * Generated by GitHub Copilot (GPT-5.4)
 */
final class AnalyzePathResolver {

	private static final Logger LOGGER = LogManager.getLogger(AnalyzePathResolver.class);

	List<Path> resolveAnalyzeTargets(final List<String> patterns) throws IOException {
		final LinkedHashSet<Path> resolved = new LinkedHashSet<Path>();
		for (final String pattern : patterns) {
			resolvePattern(pattern, resolved);
		}
		return new ArrayList<Path>(resolved);
	}

	private void resolvePattern(final String pattern, final LinkedHashSet<Path> resolved) throws IOException {
		final String absolutePattern = toAbsolutePattern(pattern);
		LOGGER.debug("Resolving analyze pattern: {}", absolutePattern);
		if (!containsWildcard(absolutePattern)) {
			final Path path = Paths.get(normalizePath(absolutePattern)).normalize();
			if (Files.isRegularFile(path) && isAnalyzeTarget(path)) {
				resolved.add(path.toAbsolutePath().normalize());
			}
			return;
		}
		final Path searchRoot = determineSearchRoot(absolutePattern);
		if (!Files.exists(searchRoot)) {
			return;
		}
		final Pattern regex = Pattern.compile(globToRegex(normalizePath(absolutePattern)));
		Files.walk(searchRoot)
			.filter(Files::isRegularFile)
			.filter(AnalyzePathResolver::isAnalyzeTarget)
			.forEach(path -> {
				final String normalizedPath = normalizePath(path.toAbsolutePath().toString());
				if (regex.matcher(normalizedPath).matches()) {
					resolved.add(path.toAbsolutePath().normalize());
				}
			});
	}

	private static String toAbsolutePattern(final String pattern) {
		if (isAbsolutePattern(pattern)) {
			return normalizePath(pattern);
		}
		final Path base = Paths.get("").toAbsolutePath();
		final Path resolvedPattern = base.resolve(pattern).normalize();
		return normalizePath(resolvedPattern.toString());
	}

	private static boolean isAbsolutePattern(final String pattern) {
		final String normalized = normalizePath(pattern);
		return normalized.startsWith("/")
			|| (normalized.length() >= 3 && Character.isLetter(normalized.charAt(0)) && normalized.charAt(1) == ':'
				&& normalized.charAt(2) == '/');
	}

	private static boolean containsWildcard(final String pattern) {
		return pattern.indexOf('*') >= 0 || pattern.indexOf('?') >= 0;
	}

	private static Path determineSearchRoot(final String pattern) {
		final String normalized = normalizePath(pattern);
		final int wildcardIndex = firstWildcardIndex(normalized);
		if (wildcardIndex < 0) {
			return Paths.get(normalized).toAbsolutePath().normalize();
		}
		final int separatorIndex = normalized.lastIndexOf('/', wildcardIndex);
		if (separatorIndex < 0) {
			return Paths.get("").toAbsolutePath().normalize();
		}
		String root = normalized.substring(0, separatorIndex);
		if (root.isEmpty()) {
			root = ".";
		}
		if (root.length() == 2 && root.charAt(1) == ':') {
			root = root + '/';
		}
		return Paths.get(root).toAbsolutePath().normalize();
	}

	private static int firstWildcardIndex(final String pattern) {
		final int starIndex = pattern.indexOf('*');
		final int questionIndex = pattern.indexOf('?');
		if (starIndex < 0) {
			return questionIndex;
		}
		if (questionIndex < 0) {
			return starIndex;
		}
		return Math.min(starIndex, questionIndex);
	}

	private static boolean isAnalyzeTarget(final Path path) {
		final String lowerName = path.getFileName().toString().toLowerCase();
		return lowerName.endsWith(".class") || lowerName.endsWith(".jar");
	}

	private static String normalizePath(final String path) {
		return path.replace('\\', '/');
	}

	private static String globToRegex(final String pattern) {
		final String normalized = normalizePath(pattern);
		final StringBuilder regex = new StringBuilder();
		regex.append('^');
		for (int index = 0; index < normalized.length(); index++) {
			final char current = normalized.charAt(index);
			if (current == '*') {
				final boolean doubleStar = index + 1 < normalized.length() && normalized.charAt(index + 1) == '*';
				if (doubleStar) {
					regex.append(".*");
					index++;
				} else {
					regex.append("[^/]*");
				}
			} else if (current == '?') {
				regex.append("[^/]");
			} else if (".[]{}()+-^$|".indexOf(current) >= 0) {
				regex.append('\\').append(current);
			} else {
				regex.append(current);
			}
		}
		regex.append('$');
		return regex.toString();
	}
}