package com.example.depttree.logic;

import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.Paths;
import java.util.ArrayList;
import java.util.LinkedHashSet;
import java.util.List;
import java.util.regex.Pattern;
import org.apache.logging.log4j.LogManager;
import org.apache.logging.log4j.Logger;

/**
 * Generated by GitHub Copilot (GPT-5.3-Codex)
 */
final class AnalyzePathResolver {

    private static final Logger LOGGER = LogManager.getLogger(AnalyzePathResolver.class);

    List<Path> resolveAnalyzeTargets(List<String> patterns) throws IOException {
        LinkedHashSet<Path> resolved = new LinkedHashSet<Path>();
        for (String pattern : patterns) {
            resolvePattern(pattern, resolved);
        }
        List<Path> result = new ArrayList<Path>(resolved);
        LOGGER.debug("Resolved analyze targets size={}", Integer.valueOf(result.size()));
        return result;
    }

    private void resolvePattern(String pattern, LinkedHashSet<Path> output) throws IOException {
        String absolutePattern = toAbsolutePattern(pattern);
        if (!containsWildcard(absolutePattern)) {
            Path directPath = Paths.get(absolutePattern).normalize();
            if (Files.isRegularFile(directPath) && isAnalyzeTarget(directPath)) {
                output.add(directPath);
            }
            return;
        }

        Path searchRoot = determineSearchRoot(absolutePattern);
        if (!Files.exists(searchRoot)) {
            LOGGER.debug("Search root not found: {}", searchRoot.toString());
            return;
        }

        Pattern regex = Pattern.compile(globToRegex(normalizePath(absolutePattern)), Pattern.CASE_INSENSITIVE);
        Files.walk(searchRoot)
            .filter(Files::isRegularFile)
            .filter(AnalyzePathResolver::isAnalyzeTarget)
            .forEach(path -> {
                String candidate = normalizePath(path.toAbsolutePath().normalize().toString());
                if (regex.matcher(candidate).matches()) {
                    output.add(path.toAbsolutePath().normalize());
                }
            });
    }

    private static String toAbsolutePattern(String pattern) {
        if (containsWildcard(pattern)) {
            String normalized = normalizePath(pattern);
            if (isAbsolutePattern(normalized)) {
                return normalized;
            }
            String cwd = normalizePath(Paths.get("").toAbsolutePath().normalize().toString());
            if (normalized.startsWith("./")) {
                normalized = normalized.substring(2);
            }
            return cwd + "/" + normalized;
        }

        Path path = Paths.get(pattern);
        if (path.isAbsolute()) {
            return path.normalize().toString();
        }
        return Paths.get("").toAbsolutePath().resolve(path).normalize().toString();
    }

    private static boolean isAbsolutePattern(String normalizedPattern) {
        if (normalizedPattern.startsWith("/")) {
            return true;
        }
        if (normalizedPattern.startsWith("//")) {
            return true;
        }
        return normalizedPattern.length() >= 3
            && Character.isLetter(normalizedPattern.charAt(0))
            && normalizedPattern.charAt(1) == ':'
            && normalizedPattern.charAt(2) == '/';
    }

    private static boolean containsWildcard(String path) {
        return path.indexOf('*') >= 0 || path.indexOf('?') >= 0;
    }

    private static Path determineSearchRoot(String absolutePattern) {
        String normalized = normalizePath(absolutePattern);
        int wildcardIndex = firstWildcardIndex(normalized);
        if (wildcardIndex < 0) {
            return Paths.get(absolutePattern).toAbsolutePath().normalize();
        }

        int slashIndex = normalized.substring(0, wildcardIndex).lastIndexOf('/');
        if (slashIndex < 0) {
            return Paths.get("").toAbsolutePath().normalize();
        }

        String root = normalized.substring(0, slashIndex);
        if (root.isEmpty()) {
            return Paths.get("").toAbsolutePath().normalize();
        }
        return Paths.get(root).toAbsolutePath().normalize();
    }

    private static int firstWildcardIndex(String value) {
        int star = value.indexOf('*');
        int question = value.indexOf('?');
        if (star < 0) {
            return question;
        }
        if (question < 0) {
            return star;
        }
        return Math.min(star, question);
    }

    private static boolean isAnalyzeTarget(Path path) {
        String fileName = path.getFileName().toString().toLowerCase();
        return fileName.endsWith(".class") || fileName.endsWith(".jar");
    }

    private static String normalizePath(String value) {
        return value.replace('\\', '/');
    }

    private static String globToRegex(String glob) {
        StringBuilder builder = new StringBuilder();
        builder.append('^');

        for (int i = 0; i < glob.length(); i++) {
            char ch = glob.charAt(i);
            if (ch == '*') {
                boolean doubleStar = i + 1 < glob.length() && glob.charAt(i + 1) == '*';
                if (doubleStar) {
                    builder.append(".*");
                    i++;
                } else {
                    builder.append("[^/]*");
                }
                continue;
            }
            if (ch == '?') {
                builder.append("[^/]");
                continue;
            }
            if (".()[]{}+^$|\\".indexOf(ch) >= 0) {
                builder.append('\\');
            }
            builder.append(ch);
        }

        builder.append('$');
        return builder.toString();
    }
}
