package com.example.depttree.logic;

import java.io.ByteArrayOutputStream;
import java.io.IOException;
import java.io.InputStream;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.ArrayList;
import java.util.Collections;
import java.util.LinkedHashSet;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;
import java.util.Set;
import java.util.jar.JarEntry;
import java.util.jar.JarFile;
import org.apache.logging.log4j.LogManager;
import org.apache.logging.log4j.Logger;
import org.objectweb.asm.ClassReader;
import org.objectweb.asm.ClassVisitor;
import org.objectweb.asm.Label;
import org.objectweb.asm.MethodVisitor;
import org.objectweb.asm.Opcodes;

/**
 * Generated by GitHub Copilot (GPT-5.3-Codex)
 */
final class BytecodeRepository {

    private static final Logger LOGGER = LogManager.getLogger(BytecodeRepository.class);

    private final Map<String, AnalyzedClass> classes = new LinkedHashMap<String, AnalyzedClass>();
    private final Map<String, String> classSources = new LinkedHashMap<String, String>();
    private final Map<MethodKey, AnalyzedMethod> methods = new LinkedHashMap<MethodKey, AnalyzedMethod>();

    static BytecodeRepository load(List<Path> analyzeTargets) throws IOException {
        BytecodeRepository repository = new BytecodeRepository();
        for (Path target : analyzeTargets) {
            repository.loadTarget(target);
        }
        LOGGER.debug("Loaded classes={} methods={}", Integer.valueOf(repository.classes.size()), Integer.valueOf(repository.methods.size()));
        return repository;
    }

    boolean hasClass(String fqcn) {
        return classes.containsKey(fqcn);
    }

    String findClassSource(String fqcn) {
        return classSources.get(fqcn);
    }

    List<MethodKey> findRootMethods(String fqcn) {
        List<MethodKey> result = new ArrayList<MethodKey>();
        AnalyzedClass analyzedClass = classes.get(fqcn);
        if (analyzedClass == null) {
            return result;
        }

        for (AnalyzedMethod method : analyzedClass.methods) {
            if (method.isRootVisibleMethod()) {
                result.add(method.key);
            }
        }
        return result;
    }

    AnalyzedMethod findMethod(MethodKey key) {
        return methods.get(key);
    }

    List<MethodKey> resolveCallTargets(MethodCall call) {
        if (!call.isInterface) {
            List<MethodKey> singleTarget = new ArrayList<MethodKey>();
            singleTarget.add(call.toMethodKey());
            return singleTarget;
        }

        LinkedHashSet<MethodKey> resolved = new LinkedHashSet<MethodKey>();
        MethodKey interfaceMethod = call.toMethodKey();
        if (methods.containsKey(interfaceMethod)) {
            resolved.add(interfaceMethod);
        }

        for (Map.Entry<String, AnalyzedClass> entry : classes.entrySet()) {
            String className = entry.getKey();
            AnalyzedClass analyzedClass = entry.getValue();
            if (analyzedClass.isInterface || analyzedClass.isAbstract) {
                continue;
            }
            if (!implementsInterface(className, call.owner)) {
                continue;
            }

            MethodKey implementation = resolveVirtualMethod(className, call.name, call.descriptor);
            if (implementation != null) {
                resolved.add(implementation);
            }
        }

        return new ArrayList<MethodKey>(resolved);
    }

    private boolean implementsInterface(String className, String interfaceName) {
        LinkedHashSet<String> visited = new LinkedHashSet<String>();
        return implementsInterfaceRecursive(className, interfaceName, visited);
    }

    private boolean implementsInterfaceRecursive(String className, String interfaceName, Set<String> visited) {
        if (className == null || !visited.add(className)) {
            return false;
        }

        AnalyzedClass analyzedClass = classes.get(className);
        if (analyzedClass == null) {
            return false;
        }

        for (String implementedInterface : analyzedClass.interfaces) {
            if (interfaceName.equals(implementedInterface)) {
                return true;
            }
            if (implementsInterfaceRecursive(implementedInterface, interfaceName, visited)) {
                return true;
            }
        }

        return implementsInterfaceRecursive(analyzedClass.superClassName, interfaceName, visited);
    }

    private MethodKey resolveVirtualMethod(String owner, String name, String descriptor) {
        String current = owner;
        while (current != null) {
            MethodKey candidate = new MethodKey(current, name, descriptor);
            if (methods.containsKey(candidate)) {
                return candidate;
            }

            AnalyzedClass analyzedClass = classes.get(current);
            if (analyzedClass == null) {
                break;
            }
            current = analyzedClass.superClassName;
        }
        return null;
    }

    private void loadTarget(Path target) throws IOException {
        String fileName = target.getFileName().toString().toLowerCase();
        if (fileName.endsWith(".class")) {
            parseClassBytes(Files.readAllBytes(target), target.toString());
            return;
        }
        if (fileName.endsWith(".jar")) {
            loadJar(target);
        }
    }

    private void loadJar(Path jarPath) throws IOException {
        JarFile jarFile = new JarFile(jarPath.toFile());
        try {
            for (JarEntry entry : Collections.list(jarFile.entries())) {
                if (!entry.getName().endsWith(".class")) {
                    continue;
                }
                InputStream in = jarFile.getInputStream(entry);
                try {
                    parseClassBytes(readAllBytes(in), jarPath.toString() + "!" + entry.getName());
                } finally {
                    in.close();
                }
            }
        } finally {
            jarFile.close();
        }
    }

    private void parseClassBytes(byte[] classBytes, String source) {
        try {
            ClassReader classReader = new ClassReader(classBytes);
            classReader.accept(new RepositoryClassVisitor(source), ClassReader.SKIP_DEBUG | ClassReader.SKIP_FRAMES);
        } catch (Exception e) {
            LOGGER.debug("Skipped unreadable class source={} reason={}", source, e.getMessage());
        }
    }

    private static byte[] readAllBytes(InputStream inputStream) throws IOException {
        ByteArrayOutputStream output = new ByteArrayOutputStream();
        byte[] buffer = new byte[8192];
        int read;
        while ((read = inputStream.read(buffer)) >= 0) {
            output.write(buffer, 0, read);
        }
        return output.toByteArray();
    }

    private final class RepositoryClassVisitor extends ClassVisitor {

        private final String source;
        private String currentClassName;
        private String currentSuperClassName;
        private List<String> currentInterfaces = new ArrayList<String>();
        private boolean currentIsInterface;
        private boolean currentIsAbstract;
        private final List<AnalyzedMethod> currentMethods = new ArrayList<AnalyzedMethod>();

        private RepositoryClassVisitor(String source) {
            super(Opcodes.ASM9);
            this.source = source;
        }

        @Override
        public void visit(int version, int access, String name, String signature, String superName, String[] interfaces) {
            this.currentClassName = name.replace('/', '.');
            this.currentSuperClassName = superName == null ? null : superName.replace('/', '.');
            this.currentInterfaces = toClassNames(interfaces);
            this.currentIsInterface = (access & Opcodes.ACC_INTERFACE) != 0;
            this.currentIsAbstract = (access & Opcodes.ACC_ABSTRACT) != 0;
            this.currentMethods.clear();
        }

        @Override
        public MethodVisitor visitMethod(int access, String name, String descriptor, String signature, String[] exceptions) {
            if ((access & (Opcodes.ACC_SYNTHETIC | Opcodes.ACC_BRIDGE)) != 0) {
                return null;
            }

            MethodKey key = new MethodKey(currentClassName, name, descriptor);
            AnalyzedMethod method = new AnalyzedMethod(key, access);
            currentMethods.add(method);
            methods.put(key, method);

            return new MethodVisitor(Opcodes.ASM9) {

                private final Set<Label> catchHandlerLabels = new LinkedHashSet<Label>();
                private final Set<Label> nonCatchJumpTargets = new LinkedHashSet<Label>();
                private boolean inCatchHandler;

                @Override
                public void visitTryCatchBlock(Label start, Label end, Label handler, String type) {
                    if (type != null) {
                        catchHandlerLabels.add(handler);
                    }
                }

                @Override
                public void visitLabel(Label label) {
                    if (catchHandlerLabels.contains(label)) {
                        inCatchHandler = true;
                        return;
                    }
                    // Catch block that falls through to a merge label should stop being marked as exception flow.
                    if (inCatchHandler && nonCatchJumpTargets.contains(label)) {
                        inCatchHandler = false;
                    }
                }

                @Override
                public void visitMethodInsn(int opcode, String owner, String calledName, String calledDesc, boolean isInterface) {
                    if ("<init>".equals(calledName) || "<clinit>".equals(calledName)) {
                        return;
                    }
                    method.calls.add(new MethodCall(owner.replace('/', '.'), calledName, calledDesc, isInterface, inCatchHandler));
                }

                @Override
                public void visitInsn(int opcode) {
                    if (inCatchHandler && isMethodExitOpcode(opcode)) {
                        inCatchHandler = false;
                    }
                }

                @Override
                public void visitJumpInsn(int opcode, Label label) {
                    if (!inCatchHandler) {
                        nonCatchJumpTargets.add(label);
                    }
                    if (inCatchHandler && opcode == Opcodes.GOTO) {
                        inCatchHandler = false;
                    }
                }

                @Override
                public void visitLookupSwitchInsn(Label dflt, int[] keys, Label[] labels) {
                    if (inCatchHandler) {
                        return;
                    }
                    nonCatchJumpTargets.add(dflt);
                    for (Label label : labels) {
                        nonCatchJumpTargets.add(label);
                    }
                }

                @Override
                public void visitTableSwitchInsn(int min, int max, Label dflt, Label... labels) {
                    if (inCatchHandler) {
                        return;
                    }
                    nonCatchJumpTargets.add(dflt);
                    for (Label label : labels) {
                        nonCatchJumpTargets.add(label);
                    }
                }

                private boolean isMethodExitOpcode(int opcode) {
                    return opcode == Opcodes.IRETURN
                        || opcode == Opcodes.LRETURN
                        || opcode == Opcodes.FRETURN
                        || opcode == Opcodes.DRETURN
                        || opcode == Opcodes.ARETURN
                        || opcode == Opcodes.RETURN
                        || opcode == Opcodes.ATHROW;
                }
            };
        }

        @Override
        public void visitEnd() {
            classes.put(
                currentClassName,
                new AnalyzedClass(currentMethods, currentSuperClassName, currentInterfaces, currentIsInterface, currentIsAbstract)
            );
            if (!classSources.containsKey(currentClassName)) {
                classSources.put(currentClassName, source);
            }
        }
    }

    private static List<String> toClassNames(String[] internalNames) {
        List<String> classNames = new ArrayList<String>();
        if (internalNames == null) {
            return classNames;
        }
        for (String internalName : internalNames) {
            classNames.add(internalName.replace('/', '.'));
        }
        return classNames;
    }

    static final class MethodCall {
        final String owner;
        final String name;
        final String descriptor;
        final boolean isInterface;
        final boolean fromExceptionHandler;

        MethodCall(String owner, String name, String descriptor, boolean isInterface, boolean fromExceptionHandler) {
            this.owner = owner;
            this.name = name;
            this.descriptor = descriptor;
            this.isInterface = isInterface;
            this.fromExceptionHandler = fromExceptionHandler;
        }

        MethodKey toMethodKey() {
            return new MethodKey(owner, name, descriptor);
        }
    }

    static final class AnalyzedMethod {
        final MethodKey key;
        final int access;
        final List<MethodCall> calls = new ArrayList<MethodCall>();

        AnalyzedMethod(MethodKey key, int access) {
            this.key = key;
            this.access = access;
        }

        boolean isRootVisibleMethod() {
            if ("<init>".equals(key.name) || "<clinit>".equals(key.name)) {
                return false;
            }
            return (access & Opcodes.ACC_PRIVATE) == 0;
        }
    }

    private static final class AnalyzedClass {
        final List<AnalyzedMethod> methods;
        final String superClassName;
        final List<String> interfaces;
        final boolean isInterface;
        final boolean isAbstract;

        AnalyzedClass(
            List<AnalyzedMethod> methods,
            String superClassName,
            List<String> interfaces,
            boolean isInterface,
            boolean isAbstract
        ) {
            this.methods = new ArrayList<AnalyzedMethod>(methods);
            this.superClassName = superClassName;
            this.interfaces = new ArrayList<String>(interfaces);
            this.isInterface = isInterface;
            this.isAbstract = isAbstract;
        }
    }
}
