package com.example.depttree.logic;

import java.io.IOException;
import java.io.InputStream;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.ArrayList;
import java.util.Collections;
import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;
import java.util.jar.JarEntry;
import java.util.jar.JarInputStream;

import org.apache.logging.log4j.LogManager;
import org.apache.logging.log4j.Logger;
import org.objectweb.asm.ClassReader;
import org.objectweb.asm.Opcodes;
import org.objectweb.asm.tree.AbstractInsnNode;
import org.objectweb.asm.tree.ClassNode;
import org.objectweb.asm.tree.JumpInsnNode;
import org.objectweb.asm.tree.LabelNode;
import org.objectweb.asm.tree.LookupSwitchInsnNode;
import org.objectweb.asm.tree.MethodInsnNode;
import org.objectweb.asm.tree.MethodNode;
import org.objectweb.asm.tree.TableSwitchInsnNode;
import org.objectweb.asm.tree.TryCatchBlockNode;

/**
 * Generated by GitHub Copilot (GPT-5.4)
 */
final class BytecodeRepository {

	private static final Logger LOGGER = LogManager.getLogger(BytecodeRepository.class);

	private final Map<String, AnalyzedClass> classes = new HashMap<String, AnalyzedClass>();
	private final Map<String, String> classSources = new HashMap<String, String>();
	private final Map<MethodKey, AnalyzedMethod> methods = new HashMap<MethodKey, AnalyzedMethod>();

	BytecodeRepository() {
	}

	static BytecodeRepository load(final List<Path> targets) throws IOException {
		final BytecodeRepository repository = new BytecodeRepository();
		for (final Path target : targets) {
			repository.loadTarget(target);
		}
		return repository;
	}

	boolean hasClass(final String className) {
		return classes.containsKey(className);
	}

	String findClassSource(final String className) {
		return classSources.get(className);
	}

	List<MethodKey> findRootMethods(final String className) {
		final AnalyzedClass analyzedClass = classes.get(className);
		if (analyzedClass == null) {
			return Collections.emptyList();
		}
		final List<MethodKey> rootMethods = new ArrayList<MethodKey>();
		for (final MethodKey methodKey : analyzedClass.orderedMethods) {
			final AnalyzedMethod analyzedMethod = methods.get(methodKey);
			if (analyzedMethod == null) {
				continue;
			}
			if ((analyzedMethod.access & Opcodes.ACC_PRIVATE) != 0) {
				continue;
			}
			if ((analyzedMethod.access & Opcodes.ACC_SYNTHETIC) != 0 || (analyzedMethod.access & Opcodes.ACC_BRIDGE) != 0) {
				continue;
			}
			rootMethods.add(methodKey);
		}
		return rootMethods;
	}

	AnalyzedMethod findMethod(final MethodKey methodKey) {
		return methods.get(methodKey);
	}

	List<MethodKey> resolveCallTargets(final MethodCall methodCall) {
		final LinkedHashSet<MethodKey> resolved = new LinkedHashSet<MethodKey>();
		final MethodKey declaredKey = new MethodKey(methodCall.owner, methodCall.name, methodCall.descriptor);
		final AnalyzedMethod declaredMethod = methods.get(declaredKey);
		if (declaredMethod != null) {
			resolved.add(declaredKey);
		}
		if (methodCall.interfaceInvocation) {
			for (final AnalyzedClass analyzedClass : classes.values()) {
				if (!analyzedClass.concrete) {
					continue;
				}
				if (!implementsInterface(analyzedClass.name, methodCall.owner)) {
					continue;
				}
				final MethodKey implementation = resolveVirtualMethod(analyzedClass.name, methodCall.name, methodCall.descriptor);
				if (implementation != null) {
					resolved.add(implementation);
				}
			}
		} else if (declaredMethod != null && declaredMethod.abstractMethod) {
			for (final AnalyzedClass analyzedClass : classes.values()) {
				if (!analyzedClass.concrete) {
					continue;
				}
				if (!isDescendantOf(analyzedClass.name, methodCall.owner)) {
					continue;
				}
				final MethodKey implementation = resolveVirtualMethod(analyzedClass.name, methodCall.name, methodCall.descriptor);
				if (implementation != null) {
					resolved.add(implementation);
				}
			}
		}
		return new ArrayList<MethodKey>(resolved);
	}

	private boolean implementsInterface(final String className, final String interfaceName) {
		return implementsInterfaceRecursive(className, interfaceName, new HashSet<String>());
	}

	private boolean implementsInterfaceRecursive(final String className, final String interfaceName,
			final Set<String> visited) {
		if (!visited.add(className)) {
			return false;
		}
		final AnalyzedClass analyzedClass = classes.get(className);
		if (analyzedClass == null) {
			return false;
		}
		if (analyzedClass.interfaces.contains(interfaceName)) {
			return true;
		}
		for (final String implementedInterface : analyzedClass.interfaces) {
			if (implementsInterfaceRecursive(implementedInterface, interfaceName, visited)) {
				return true;
			}
		}
		return analyzedClass.superName != null
			&& implementsInterfaceRecursive(analyzedClass.superName, interfaceName, visited);
	}

	private boolean isDescendantOf(final String className, final String expectedAncestor) {
		String current = className;
		while (current != null) {
			if (expectedAncestor.equals(current)) {
				return true;
			}
			final AnalyzedClass analyzedClass = classes.get(current);
			current = analyzedClass == null ? null : analyzedClass.superName;
		}
		return false;
	}

	private MethodKey resolveVirtualMethod(final String owner, final String name, final String descriptor) {
		String current = owner;
		while (current != null) {
			final MethodKey candidate = new MethodKey(current, name, descriptor);
			if (methods.containsKey(candidate)) {
				return candidate;
			}
			final AnalyzedClass analyzedClass = classes.get(current);
			current = analyzedClass == null ? null : analyzedClass.superName;
		}
		return null;
	}

	private void loadTarget(final Path target) throws IOException {
		LOGGER.debug("Loading analyze target: {}", target);
		if (Files.isDirectory(target)) {
			Files.walk(target)
				.filter(Files::isRegularFile)
				.filter(path -> path.getFileName().toString().endsWith(".class"))
				.forEach(path -> {
					try {
						parseClassBytes(Files.readAllBytes(path), path.toString());
					} catch (final IOException exception) {
						throw new IllegalStateException(exception);
					}
				});
			return;
		}
		final String fileName = target.getFileName().toString().toLowerCase();
		if (fileName.endsWith(".jar")) {
			loadJar(target);
			return;
		}
		if (fileName.endsWith(".class")) {
			parseClassBytes(Files.readAllBytes(target), target.toString());
		}
	}

	private void loadJar(final Path target) throws IOException {
		final JarInputStream jarInputStream = new JarInputStream(Files.newInputStream(target));
		try {
			JarEntry entry;
			while ((entry = jarInputStream.getNextJarEntry()) != null) {
				if (!entry.getName().endsWith(".class")) {
					continue;
				}
				parseClassBytes(readAllBytes(jarInputStream), target.toString() + "!/" + entry.getName());
			}
		} finally {
			jarInputStream.close();
		}
	}

	private void parseClassBytes(final byte[] classBytes, final String source) {
		final ClassNode classNode = new ClassNode();
		new ClassReader(classBytes).accept(classNode, 0);
		final String className = classNode.name.replace('/', '.');
		final String superName = classNode.superName == null ? null : classNode.superName.replace('/', '.');
		final List<String> interfaces = toClassNames(classNode.interfaces);
		final AnalyzedClass analyzedClass = new AnalyzedClass(className, superName, interfaces, classNode.access);
		classes.put(className, analyzedClass);
		classSources.put(className, source);
		for (final MethodNode methodNode : classNode.methods) {
			if ("<init>".equals(methodNode.name) || "<clinit>".equals(methodNode.name)) {
				continue;
			}
			final MethodKey methodKey = new MethodKey(className, methodNode.name, methodNode.desc);
			analyzedClass.orderedMethods.add(methodKey);
			methods.put(methodKey, new AnalyzedMethod(methodKey, methodNode.access, collectMethodCalls(methodNode)));
		}
	}

	private List<MethodCall> collectMethodCalls(final MethodNode methodNode) {
		final Map<AbstractInsnNode, Integer> instructionIndexes = new HashMap<AbstractInsnNode, Integer>();
		final List<LabelNode> mergeLabels = new ArrayList<LabelNode>();
		int index = 0;
		for (AbstractInsnNode instruction = methodNode.instructions.getFirst(); instruction != null; instruction = instruction.getNext()) {
			instructionIndexes.put(instruction, Integer.valueOf(index++));
			if (instruction instanceof JumpInsnNode) {
				mergeLabels.add(((JumpInsnNode) instruction).label);
			} else if (instruction instanceof TableSwitchInsnNode) {
				mergeLabels.add(((TableSwitchInsnNode) instruction).dflt);
				mergeLabels.addAll(((TableSwitchInsnNode) instruction).labels);
			} else if (instruction instanceof LookupSwitchInsnNode) {
				mergeLabels.add(((LookupSwitchInsnNode) instruction).dflt);
				mergeLabels.addAll(((LookupSwitchInsnNode) instruction).labels);
			}
		}
		final List<int[]> exceptionRanges = new ArrayList<int[]>();
		for (final TryCatchBlockNode tryCatchBlockNode : methodNode.tryCatchBlocks) {
			final Integer startIndex = instructionIndexes.get(tryCatchBlockNode.handler);
			if (startIndex == null) {
				continue;
			}
			int endIndex = methodNode.instructions.size();
			for (AbstractInsnNode cursor = tryCatchBlockNode.handler.getNext(); cursor != null; cursor = cursor.getNext()) {
				if (cursor instanceof LabelNode && mergeLabels.contains(cursor)) {
					endIndex = instructionIndexes.get(cursor).intValue();
					break;
				}
				final int opcode = cursor.getOpcode();
				if (opcode == Opcodes.GOTO || opcode == Opcodes.RETURN || opcode == Opcodes.IRETURN
					|| opcode == Opcodes.LRETURN || opcode == Opcodes.FRETURN || opcode == Opcodes.DRETURN
					|| opcode == Opcodes.ARETURN || opcode == Opcodes.ATHROW) {
					endIndex = instructionIndexes.get(cursor).intValue() + 1;
					break;
				}
			}
			exceptionRanges.add(new int[] {startIndex.intValue(), endIndex});
		}
		final List<MethodCall> calls = new ArrayList<MethodCall>();
		for (AbstractInsnNode instruction = methodNode.instructions.getFirst(); instruction != null; instruction = instruction.getNext()) {
			if (!(instruction instanceof MethodInsnNode)) {
				continue;
			}
			final MethodInsnNode methodInstruction = (MethodInsnNode) instruction;
			if ("<init>".equals(methodInstruction.name) || "<clinit>".equals(methodInstruction.name)) {
				continue;
			}
			final int currentIndex = instructionIndexes.get(instruction).intValue();
			final boolean exceptionHandler = isExceptionHandlerInstruction(currentIndex, exceptionRanges);
			calls.add(new MethodCall(methodInstruction.owner.replace('/', '.'), methodInstruction.name,
				methodInstruction.desc, exceptionHandler,
				methodInstruction.getOpcode() == Opcodes.INVOKEINTERFACE));
		}
		return calls;
	}

	private static boolean isExceptionHandlerInstruction(final int index, final List<int[]> exceptionRanges) {
		for (final int[] range : exceptionRanges) {
			if (index >= range[0] && index < range[1]) {
				return true;
			}
		}
		return false;
	}

	private static byte[] readAllBytes(final InputStream inputStream) throws IOException {
		final byte[] buffer = new byte[8192];
		int read;
		final java.io.ByteArrayOutputStream outputStream = new java.io.ByteArrayOutputStream();
		while ((read = inputStream.read(buffer)) >= 0) {
			outputStream.write(buffer, 0, read);
		}
		return outputStream.toByteArray();
	}

	private static List<String> toClassNames(final List<String> internalNames) {
		final List<String> classNames = new ArrayList<String>(internalNames.size());
		for (final String internalName : internalNames) {
			classNames.add(internalName.replace('/', '.'));
		}
		return classNames;
	}

	static final class AnalyzedClass {

		final String name;
		final String superName;
		final List<String> interfaces;
		final boolean concrete;
		final List<MethodKey> orderedMethods = new ArrayList<MethodKey>();

		AnalyzedClass(final String name, final String superName, final List<String> interfaces, final int access) {
			this.name = name;
			this.superName = superName;
			this.interfaces = interfaces;
			this.concrete = (access & (Opcodes.ACC_INTERFACE | Opcodes.ACC_ABSTRACT)) == 0;
		}
	}

	static final class AnalyzedMethod {

		final MethodKey methodKey;
		final int access;
		final boolean abstractMethod;
		final List<MethodCall> methodCalls;

		AnalyzedMethod(final MethodKey methodKey, final int access, final List<MethodCall> methodCalls) {
			this.methodKey = methodKey;
			this.access = access;
			this.abstractMethod = (access & Opcodes.ACC_ABSTRACT) != 0;
			this.methodCalls = methodCalls;
		}
	}

	static final class MethodCall {

		final String owner;
		final String name;
		final String descriptor;
		final boolean exceptionHandler;
		final boolean interfaceInvocation;

		MethodCall(final String owner, final String name, final String descriptor, final boolean exceptionHandler,
				final boolean interfaceInvocation) {
			this.owner = owner;
			this.name = name;
			this.descriptor = descriptor;
			this.exceptionHandler = exceptionHandler;
			this.interfaceInvocation = interfaceInvocation;
		}
	}
}