package com.example.depttree.logic;

import java.util.ArrayList;
import java.util.LinkedHashSet;
import java.util.List;
import java.util.Set;

import org.apache.logging.log4j.LogManager;
import org.apache.logging.log4j.Logger;

import com.example.depttree.logic.BytecodeRepository.AnalyzedMethod;
import com.example.depttree.logic.BytecodeRepository.MethodCall;

/**
 * Generated by GitHub Copilot (GPT-5.4)
 */
final class CallTreeService {

	private static final Logger LOGGER = LogManager.getLogger(CallTreeService.class);
	private static final String LINE_SEPARATOR = System.lineSeparator();

	private final BytecodeRepository repository;
	private final int maxDepth;

	CallTreeService(final BytecodeRepository repository, final int maxDepth) {
		this.repository = repository;
		this.maxDepth = maxDepth;
	}

	String buildTrees(final List<MethodKey> rootMethods) {
		final List<String> trees = new ArrayList<String>();
		for (final MethodKey rootMethod : rootMethods) {
			trees.add(buildTree(rootMethod));
		}
		return joinWithThreeBlankLines(trees);
	}

	String buildTree(final MethodKey rootMethod) {
		final List<String> lines = new ArrayList<String>();
		lines.add(LINE_SEPARATOR);
		lines.add("# ===========");
		lines.add("# root method ( " + rootMethod.name + " )");
		lines.add("# ===========");
		lines.add(MethodSignatureFormatter.format(rootMethod));
		renderChildren(rootMethod, 1, "", new LinkedHashSet<MethodKey>(), lines);
		return joinLines(lines);
	}

	private void renderChildren(final MethodKey currentMethod, final int depth, final String prefix,
			final Set<MethodKey> stack, final List<String> lines) {
		final AnalyzedMethod analyzedMethod = repository.findMethod(currentMethod);
		if (analyzedMethod == null) {
			return;
		}

		LOGGER.debug("Rendering children. method={}, depth={}, prefix={}, stack={}", currentMethod.name, depth, prefix,
			stack);

		stack.add(currentMethod);
		final List<RenderNode> children = new ArrayList<RenderNode>();

		/*
		 * 現在のメソッドから見つかった呼び出し先を走査し、除外対象は無視する。
		 * 深さ制限に達した呼び出しは MAX として記録し、呼び出し先を解決できない場合は
		 * UNRESOLVED として保持する。解決できた呼び出し先は後続の描画対象として追加する。
		 */
		for (final MethodCall methodCall : analyzedMethod.methodCalls) {
			if (repository.isExcludedClass(methodCall.owner)) {
				continue;
			}
			if (depth >= maxDepth) {
				children.add(RenderNode.max(methodCall.exceptionHandler));
				continue;
			}
			final List<MethodKey> targets = repository.resolveCallTargets(methodCall);
			if (targets.isEmpty()) {
				children.add(RenderNode.unresolved(new MethodKey(methodCall.owner, methodCall.name, methodCall.descriptor),
					methodCall.exceptionHandler));
				continue;
			}
			for (final MethodKey target : targets) {
				children.add(RenderNode.resolved(target, methodCall.exceptionHandler));
			}
		}

		/*
		 * 収集した子ノードをツリー形式の文字列として順番に出力する。
		 * 深さ上限・未解決・循環参照は専用ラベル付きで描画し、通常の呼び出し先だけ
		 * 次の階層へ再帰して、枝線の接頭辞も末尾ノードかどうかで切り替える。
		 */
		for (int index = 0; index < children.size(); index++) {
			final RenderNode child = children.get(index);
			final boolean last = index == children.size() - 1;
			lines.add(prefix + " |");
			if (child.maxDepth) {
				lines.add(prefix + " `--- " + child.prefix + "[MAX]");
				continue;
			}
			final MethodKey target = child.methodKey;
			final String signature = MethodSignatureFormatter.format(target);
			if (child.unresolved) {
				lines.add(prefix + " `--- " + child.prefix + "[UNRESOLVED] " + signature);
				continue;
			}
			if (stack.contains(target)) {
				lines.add(prefix + " `--- " + child.prefix + "[CIRCULAR] " + signature);
				continue;
			}
			lines.add(prefix + " `--- " + child.prefix + signature);
			final String childPrefix = prefix + (last ? "       " : " |     ");
			final Set<MethodKey> childStack = new LinkedHashSet<MethodKey>(stack);
			renderChildren(target, depth + 1, childPrefix, childStack, lines);
		}
	}

	private static String joinLines(final List<String> lines) {
		return String.join(LINE_SEPARATOR, lines);
	}

	private static String joinWithThreeBlankLines(final List<String> trees) {
		return String.join(repeatLineSeparator(4), trees);
	}

	private static String repeatLineSeparator(final int count) {
		final StringBuilder builder = new StringBuilder();
		for (int index = 0; index < count; index++) {
			builder.append(LINE_SEPARATOR);
		}
		return builder.toString();
	}

	private static final class RenderNode {

		private final MethodKey methodKey;
		private final boolean unresolved;
		private final boolean maxDepth;
		private final String prefix;

		private RenderNode(final MethodKey methodKey, final boolean unresolved, final boolean maxDepth,
				final boolean exceptionHandler) {
			this.methodKey = methodKey;
			this.unresolved = unresolved;
			this.maxDepth = maxDepth;
			this.prefix = exceptionHandler ? "[EXCEPTION] " : "";
		}

		private static RenderNode resolved(final MethodKey methodKey, final boolean exceptionHandler) {
			return new RenderNode(methodKey, false, false, exceptionHandler);
		}

		private static RenderNode unresolved(final MethodKey methodKey, final boolean exceptionHandler) {
			return new RenderNode(methodKey, true, false, exceptionHandler);
		}

		private static RenderNode max(final boolean exceptionHandler) {
			return new RenderNode(null, false, true, exceptionHandler);
		}
	}
}