package com.example.depttree.logic;

import java.util.ArrayList;
import java.util.LinkedHashSet;
import java.util.List;
import java.util.Set;

/**
 * Generated by GitHub Copilot (GPT-5.3-Codex)
 */
final class CallTreeService {

    private final BytecodeRepository repository;
    private final int maxDepth;

    CallTreeService(BytecodeRepository repository, int maxDepth) {
        this.repository = repository;
        this.maxDepth = maxDepth;
    }

    String buildTrees(List<MethodKey> rootMethods) {
        List<String> blocks = new ArrayList<String>();
        for (MethodKey root : rootMethods) {
            blocks.add(buildSingleTree(root));
        }
        return joinWithThreeBlankLines(blocks);
    }

    private String buildSingleTree(MethodKey root) {
        List<String> lines = new ArrayList<String>();
        lines.add(MethodSignatureFormatter.format(root));
        renderChildren(root, 1, "", new LinkedHashSet<MethodKey>(), lines);
        return joinLines(lines);
    }

    private void renderChildren(
        MethodKey current,
        int currentDepth,
        String prefix,
        Set<MethodKey> path,
        List<String> lines
    ) {
        path.add(current);

        BytecodeRepository.AnalyzedMethod analyzedMethod = repository.findMethod(current);
        if (analyzedMethod == null) {
            path.remove(current);
            return;
        }

        for (BytecodeRepository.MethodCall call : analyzedMethod.calls) {
            if (isExcludedPackage(call.owner)) {
                continue;
            }

            List<MethodKey> targetKeys = repository.resolveCallTargets(call);
            if (targetKeys.isEmpty()) {
                targetKeys = new ArrayList<MethodKey>();
                targetKeys.add(call.toMethodKey());
            }

            for (MethodKey targetKey : targetKeys) {
                String callPrefix = call.fromExceptionHandler ? "[EXCEPTION] " : "";
                lines.add(prefix + " |");
                if (currentDepth + 1 > maxDepth) {
                    lines.add(prefix + " `--- " + callPrefix + "[MAX]");
                    continue;
                }

                if (path.contains(targetKey)) {
                    lines.add(prefix + " `--- " + callPrefix + "[CIRCULAR] " + MethodSignatureFormatter.format(targetKey));
                    continue;
                }

                BytecodeRepository.AnalyzedMethod target = repository.findMethod(targetKey);
                if (target == null) {
                    lines.add(prefix + " `--- " + callPrefix + "[UNRESOLVED] " + MethodSignatureFormatter.format(targetKey));
                    continue;
                }

                lines.add(prefix + " `--- " + callPrefix + MethodSignatureFormatter.format(targetKey));
                renderChildren(targetKey, currentDepth + 1, prefix + " |     ", path, lines);
            }
        }

        path.remove(current);
    }

    private static boolean isExcludedPackage(String fqcn) {
        return fqcn.startsWith("java.")
            || fqcn.startsWith("javax.")
            || fqcn.startsWith("sun.")
            || fqcn.startsWith("com.sun.")
            || fqcn.startsWith("jdk.")
            || fqcn.startsWith("org.")
            || fqcn.startsWith("net.")
            || fqcn.startsWith("io.");
    }

    private static String joinLines(List<String> lines) {
        StringBuilder builder = new StringBuilder();
        for (int i = 0; i < lines.size(); i++) {
            if (i > 0) {
                builder.append('\n');
            }
            builder.append(lines.get(i));
        }
        return builder.toString();
    }

    private static String joinWithThreeBlankLines(List<String> blocks) {
        StringBuilder builder = new StringBuilder();
        for (int i = 0; i < blocks.size(); i++) {
            if (i > 0) {
                builder.append("\n\n\n\n");
            }
            builder.append(blocks.get(i));
        }
        return builder.toString();
    }
}
