package com.example.depttree.logic;

import java.util.ArrayList;
import java.util.List;
import picocli.CommandLine.Command;
import picocli.CommandLine.Option;

/**
 * Generated by GitHub Copilot (GPT-5.3-Codex)
 */
@Command(name = "dept-tree", mixinStandardHelpOptions = false)
final class CliOptions {

    @Option(
        names = {"-a", "--analyze"},
        required = true,
        arity = "1..*",
        description = "Class/jar files to analyze. Supports multiple values."
    )
    List<String> analyze = new ArrayList<String>();

    @Option(
        names = {"-r", "--root"},
        required = true,
        description = "Root class FQDN."
    )
    String rootClass;

    @Option(
        names = {"-d", "--depth"},
        defaultValue = "20",
        description = "Depth limit. Range: 1 to 100."
    )
    int depth;

    @Option(
        names = {"-h", "--help"},
        usageHelp = true,
        description = "Show help and exit."
    )
    boolean help;
}
