package com.example.depttree.logic;

import java.util.ArrayList;
import java.util.List;

import picocli.CommandLine.Command;
import picocli.CommandLine.Option;

/**
 * Generated by GitHub Copilot (GPT-5.4)
 */
@Command(name = "dept-tree", sortOptions = false)
final class CliOptions {

	@Option(names = {"-a", "--analyze"}, required = true, arity = "1..*", description = "解析するclassまたはjarファイル")
	List<String> analyze = new ArrayList<String>();

	@Option(names = {"-r", "--root"}, required = true, description = "解析開始クラスのFQDN")
	String rootClass;

	@Option(names = {"-m", "--marker"}, description = "カウント対象クラス一覧ファイル")
	String markerPath;

	@Option(names = {"-d", "--depth"}, defaultValue = "20", description = "解析深度")
	int depth;

	@Option(names = {"-h", "--help"}, usageHelp = true, description = "ヘルプを表示")
	boolean help;
}