package com.example.depttree.logic;

import java.io.PrintWriter;
import java.io.StringWriter;
import java.nio.file.Path;
import java.util.Arrays;
import java.util.List;
import org.apache.logging.log4j.LogManager;
import org.apache.logging.log4j.Logger;
import picocli.CommandLine;

/**
 * Generated by GitHub Copilot (GPT-5.3-Codex)
 */
public class DeptTreeApplication {

    private static final Logger LOGGER = LogManager.getLogger(DeptTreeApplication.class);

    /**
     * Run the application.
     *
     * @param args command line arguments
     * @return 0 when successful, 1 on failure
     */
    public int run(String[] args) {
        long startNanos = System.nanoTime();
        LOGGER.info("DeptTreeApplication.run start args={}", Arrays.toString(args));

        try {
            CliOptions options = new CliOptions();
            CommandLine commandLine = new CommandLine(options);

            CommandLine.ParseResult parseResult = commandLine.parseArgs(args);
            if (parseResult.isUsageHelpRequested()) {
                StringWriter sw = new StringWriter();
                PrintWriter pw = new PrintWriter(sw);
                commandLine.usage(pw, CommandLine.Help.Ansi.OFF);
                pw.flush();
                LOGGER.info("{}{}", System.lineSeparator(), sw.toString().trim());
                return 0;
            }

            validateDepth(options.depth);

            AnalyzePathResolver resolver = new AnalyzePathResolver();
            List<Path> analyzeTargets = resolver.resolveAnalyzeTargets(options.analyze);
            if (analyzeTargets.isEmpty()) {
                throw new IllegalArgumentException("No class/jar files were found by --analyze.");
            }

            BytecodeRepository repository = BytecodeRepository.load(analyzeTargets);
            if (!repository.hasClass(options.rootClass)) {
                throw new IllegalArgumentException("Root class not found in analyze targets: " + options.rootClass);
            }
            LOGGER.info("Root class found class={} source={}", options.rootClass, repository.findClassSource(options.rootClass));

            List<MethodKey> rootMethods = repository.findRootMethods(options.rootClass);
            if (rootMethods.isEmpty()) {
                throw new IllegalArgumentException("No public/protected/package-private methods found in root class: " + options.rootClass);
            }
            for (MethodKey rootMethod : rootMethods) {
                LOGGER.info("Root method found: {}", MethodSignatureFormatter.format(rootMethod));
            }

            CallTreeService callTreeService = new CallTreeService(repository, options.depth);
            String treeOutput = callTreeService.buildTrees(rootMethods);
            LOGGER.info("{}{}", System.lineSeparator(), treeOutput);
            return 0;
        } catch (CommandLine.ParameterException e) {
            LOGGER.error("Invalid arguments: {}", e.getMessage());
            return 1;
        } catch (Exception e) {
            LOGGER.error("Application failed.", e);
            return 1;
        } finally {
            long elapsedMs = (System.nanoTime() - startNanos) / 1_000_000L;
            LOGGER.info("DeptTreeApplication.run end elapsedMs={}", Long.valueOf(elapsedMs));
        }
    }

    private static void validateDepth(int depth) {
        if (depth < 1 || depth > 100) {
            throw new IllegalArgumentException("--depth must be between 1 and 100: " + depth);
        }
    }
}
