package com.example.depttree.logic;

import java.io.IOException;
import java.io.PrintWriter;
import java.io.StringWriter;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.Paths;
import java.nio.file.StandardCopyOption;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.LinkedHashMap;
import java.util.LinkedHashSet;
import java.util.List;
import java.util.Map;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import java.util.stream.Collectors;
import java.util.jar.JarEntry;
import java.util.jar.JarInputStream;

import org.apache.logging.log4j.LogManager;
import org.apache.logging.log4j.Logger;

import picocli.CommandLine;
import picocli.CommandLine.ParameterException;

/**
 * Generated by GitHub Copilot (GPT-5.4)
 */
public class DeptTreeApplication {

	private static final Logger LOGGER = LogManager.getLogger(DeptTreeApplication.class);
	private static final Pattern TREE_CLASS_PATTERN = Pattern.compile(
		"(?:\\[UNRESOLVED\\] |\\[EXCEPTION\\] |\\[CIRCULAR\\] )?([A-Za-z_$][\\w$]*(?:\\.[A-Za-z_$][\\w$]*)*)#");

	/**
	 * アプリケーション本体を実行します。
	 *
	 * @param args CLI引数
	 * @return 終了コード
	 */
	public int run(final String[] args) {
		LOGGER.info("DeptTreeApplication.run started. args={}", Arrays.toString(args));
		try {
			final CliOptions options = new CliOptions();
			final CommandLine commandLine = new CommandLine(options);
			try {
				commandLine.parseArgs(args);
			} catch (final ParameterException exception) {
				LOGGER.error(exception.getMessage(), exception);
				return 1;
			}
			if (options.help) {
				final StringWriter usageWriter = new StringWriter();
				commandLine.usage(new PrintWriter(usageWriter));
				LOGGER.info("{}", usageWriter.toString().trim());
				return 0;
			}
			validateDepth(options.depth);
			final AnalyzePathResolver pathResolver = new AnalyzePathResolver();
			List<Path> analyzeTargets = pathResolver.resolveAnalyzeTargets(options.analyze);
			if (analyzeTargets.isEmpty()) {
				throw new IllegalArgumentException("No analyze targets were found.");
			}
			analyzeTargets = expandJarTargets(analyzeTargets);
			final BytecodeRepository repository = BytecodeRepository.load(analyzeTargets);
			if (!repository.hasClass(options.rootClass)) {
				throw new IllegalArgumentException("Root class was not found in analyze targets: " + options.rootClass);
			}
			LOGGER.info("Root class source: {}", repository.findClassSource(options.rootClass));
			final List<MethodKey> rootMethods = repository.findRootMethods(options.rootClass);
			if (rootMethods.isEmpty()) {
				throw new IllegalArgumentException("No root methods were found: " + options.rootClass);
			}
			LOGGER.info("Root methods: {}", rootMethods.stream().map(method -> method.name).collect(Collectors.toList()));
			final CallTreeService callTreeService = new CallTreeService(repository, options.depth);
			final String treeOutput = callTreeService.buildTrees(rootMethods);
			final LinkedHashSet<String> markerClasses = loadMarkerClasses(options.markerPath);
			if (markerClasses.isEmpty()) {
				LOGGER.info("{}", treeOutput);
			} else {
				LOGGER.info("{}\n\n\n{}", treeOutput, buildMarkerReport(treeOutput, markerClasses));
			}
			return 0;
		} catch (final Exception exception) {
			LOGGER.error("Application failed.", exception);
			return 1;
		} finally {
			LOGGER.info("DeptTreeApplication.run finished.");
		}
	}

	private static void validateDepth(final int depth) {
		if (depth < 1 || depth > 100) {
			throw new IllegalArgumentException("--depth must be between 1 and 100.");
		}
	}

	private static List<Path> expandJarTargets(final List<Path> analyzeTargets) throws IOException {
		final List<Path> expandedTargets = new ArrayList<Path>();
		Path tempDirectory = null;
		for (final Path analyzeTarget : analyzeTargets) {
			final String lowerName = analyzeTarget.getFileName().toString().toLowerCase();
			if (!lowerName.endsWith(".jar")) {
				expandedTargets.add(analyzeTarget);
				continue;
			}
			if (tempDirectory == null) {
				tempDirectory = Files.createTempDirectory(Paths.get("").toAbsolutePath(), "dept-tree-");
			}
			final String baseName = analyzeTarget.getFileName().toString();
			final Path extractRoot = Files.createDirectories(tempDirectory.resolve(baseName));
			final JarInputStream jarInputStream = new JarInputStream(Files.newInputStream(analyzeTarget));
			try {
				JarEntry entry;
				while ((entry = jarInputStream.getNextJarEntry()) != null) {
					if (!entry.getName().endsWith(".class")) {
						continue;
					}
					final Path destination = extractRoot.resolve(entry.getName()).normalize();
					Files.createDirectories(destination.getParent());
					Files.copy(jarInputStream, destination, StandardCopyOption.REPLACE_EXISTING);
					expandedTargets.add(destination);
				}
			} finally {
				jarInputStream.close();
			}
		}
		return expandedTargets;
	}

	private static LinkedHashSet<String> loadMarkerClasses(final String markerPath) throws IOException {
		final LinkedHashSet<String> markerClasses = new LinkedHashSet<String>();
		if (markerPath == null || markerPath.trim().isEmpty()) {
			return markerClasses;
		}
		final Path path = Paths.get(markerPath);
		if (!Files.isRegularFile(path)) {
			throw new IllegalArgumentException("Marker file does not exist: " + markerPath);
		}
		for (final String line : Files.readAllLines(path, StandardCharsets.UTF_8)) {
			final String trimmed = line.replace("\uFEFF", "").trim();
			if (!trimmed.isEmpty()) {
				markerClasses.add(trimmed);
			}
		}
		if (markerClasses.isEmpty()) {
			throw new IllegalArgumentException("Marker file is empty: " + markerPath);
		}
		return markerClasses;
	}

	private static String buildMarkerReport(final String treeOutput, final LinkedHashSet<String> markerClasses) {
		final Map<String, Integer> counts = new LinkedHashMap<String, Integer>();
		for (final String markerClass : markerClasses) {
			counts.put(markerClass, Integer.valueOf(0));
		}
		for (final String line : treeOutput.split("\\n")) {
			final Matcher matcher = TREE_CLASS_PATTERN.matcher(line);
			if (!matcher.find()) {
				continue;
			}
			final String className = matcher.group(1);
			if (counts.containsKey(className)) {
				counts.put(className, Integer.valueOf(counts.get(className).intValue() + 1));
			}
		}
		final List<String> lines = new ArrayList<String>();
		lines.add("# ==============");
		lines.add("# marker classes report");
		lines.add("# ==============");
		for (final Map.Entry<String, Integer> entry : counts.entrySet()) {
			lines.add("* " + entry.getKey() + " (" + entry.getValue() + ")");
		}
		return String.join("\n", lines);
	}
}