package com.example.depttree.logic;

import java.util.Objects;

/**
 * Generated by GitHub Copilot (GPT-5.3-Codex)
 */
final class MethodKey {
    final String owner;
    final String name;
    final String descriptor;

    MethodKey(String owner, String name, String descriptor) {
        this.owner = owner;
        this.name = name;
        this.descriptor = descriptor;
    }

    @Override
    public boolean equals(Object other) {
        if (this == other) {
            return true;
        }
        if (!(other instanceof MethodKey)) {
            return false;
        }
        MethodKey that = (MethodKey) other;
        return Objects.equals(this.owner, that.owner)
            && Objects.equals(this.name, that.name)
            && Objects.equals(this.descriptor, that.descriptor);
    }

    @Override
    public int hashCode() {
        return Objects.hash(owner, name, descriptor);
    }
}
