package com.example.depttree.logic;

import org.objectweb.asm.Type;

/**
 * Generated by GitHub Copilot (GPT-5.4)
 */
final class MethodSignatureFormatter {

	private MethodSignatureFormatter() {
	}

	static String format(final MethodKey methodKey) {
		final Type methodType = Type.getMethodType(methodKey.descriptor);
		final Type[] argumentTypes = methodType.getArgumentTypes();
		final StringBuilder builder = new StringBuilder();
		builder.append(methodKey.owner);
		builder.append('#');
		builder.append(methodKey.name);
		builder.append('(');
		for (int index = 0; index < argumentTypes.length; index++) {
			if (index > 0) {
				builder.append(", ");
			}
			builder.append(toSimpleType(argumentTypes[index]));
		}
		builder.append(')');
		return builder.toString();
	}

	private static String toSimpleType(final Type type) {
		switch (type.getSort()) {
		case Type.VOID:
			return "void";
		case Type.BOOLEAN:
			return "boolean";
		case Type.CHAR:
			return "char";
		case Type.BYTE:
			return "byte";
		case Type.SHORT:
			return "short";
		case Type.INT:
			return "int";
		case Type.FLOAT:
			return "float";
		case Type.LONG:
			return "long";
		case Type.DOUBLE:
			return "double";
		case Type.ARRAY:
			return toSimpleType(type.getElementType()) + "[]";
		case Type.OBJECT:
			final String className = type.getClassName();
			final int separatorIndex = className.lastIndexOf('.');
			return separatorIndex >= 0 ? className.substring(separatorIndex + 1) : className;
		default:
			return type.getClassName();
		}
	}
}