package com.example.depttree.logic;

import java.util.Objects;

/**
 * Generated by GitHub Copilot (GPT-5.4)
 */
final class MethodKey {

	final String owner;
	final String name;
	final String descriptor;

	MethodKey(final String owner, final String name, final String descriptor) {
		this.owner = owner;
		this.name = name;
		this.descriptor = descriptor;
	}

	@Override
	public boolean equals(final Object other) {
		if (this == other) {
			return true;
		}
		if (!(other instanceof MethodKey)) {
			return false;
		}
		final MethodKey that = (MethodKey) other;
		return Objects.equals(owner, that.owner)
			&& Objects.equals(name, that.name)
			&& Objects.equals(descriptor, that.descriptor);
	}

	@Override
	public int hashCode() {
		return Objects.hash(owner, name, descriptor);
	}
}