package com.example.depttree.logic;

import org.objectweb.asm.Type;

/**
 * Generated by GitHub Copilot (GPT-5.3-Codex)
 */
final class MethodSignatureFormatter {

    private MethodSignatureFormatter() {
        // utility class
    }

    static String format(MethodKey key) {
        StringBuilder builder = new StringBuilder();
        builder.append(key.owner);
        builder.append('#');
        builder.append(key.name);
        builder.append('(');
        Type[] argumentTypes = Type.getArgumentTypes(key.descriptor);
        for (int i = 0; i < argumentTypes.length; i++) {
            if (i > 0) {
                builder.append(", ");
            }
            builder.append(toSimpleType(argumentTypes[i]));
        }
        builder.append(')');
        return builder.toString();
    }

    private static String toSimpleType(Type type) {
        if (type.getSort() == Type.ARRAY) {
            StringBuilder builder = new StringBuilder();
            builder.append(toSimpleType(type.getElementType()));
            for (int i = 0; i < type.getDimensions(); i++) {
                builder.append("[]");
            }
            return builder.toString();
        }

        if (type.getSort() == Type.OBJECT) {
            String className = type.getClassName();
            int dotIndex = className.lastIndexOf('.');
            String simpleName = dotIndex >= 0 ? className.substring(dotIndex + 1) : className;
            int innerIndex = simpleName.lastIndexOf('$');
            if (innerIndex >= 0) {
                return simpleName.substring(innerIndex + 1);
            }
            return simpleName;
        }

        return type.getClassName();
    }
}
