package com.example.depttree.logic;

import java.util.ArrayList;
import java.util.Collections;
import java.util.List;

/**
 * Generated by GitHub Copilot (GPT-5.4)
 */
final class PackageExclusions {

	private static final List<String> DEFAULT_PREFIX_EXCLUSIONS = createDefaultPrefixExclusions();

	private final List<String> configuredPackageExclusions;
	private final List<String> exactPackageExclusions;
	private final List<String> prefixPackageExclusions;

	private PackageExclusions(final List<String> configuredPackageExclusions,
		final List<String> exactPackageExclusions,
		final List<String> prefixPackageExclusions) {
		this.configuredPackageExclusions = configuredPackageExclusions;
		this.exactPackageExclusions = exactPackageExclusions;
		this.prefixPackageExclusions = prefixPackageExclusions;
	}

	static PackageExclusions defaultExclusions() {
		return from(Collections.<String>emptyList());
	}

	static PackageExclusions from(final List<String> configuredPackages) {
		final List<String> configuredExclusions = new ArrayList<String>(configuredPackages);
		final List<String> exactExclusions = new ArrayList<String>();
		final List<String> prefixExclusions = new ArrayList<String>(DEFAULT_PREFIX_EXCLUSIONS);
		for (final String configuredPackage : configuredPackages) {
			if (configuredPackage.endsWith(".")) {
				prefixExclusions.add(configuredPackage);
			} else {
				exactExclusions.add(configuredPackage);
			}
		}
		return new PackageExclusions(configuredExclusions, exactExclusions, prefixExclusions);
	}

	List<String> getDefaultPackageExclusions() {
		return new ArrayList<String>(DEFAULT_PREFIX_EXCLUSIONS);
	}

	List<String> getConfiguredPackageExclusions() {
		return new ArrayList<String>(configuredPackageExclusions);
	}

	boolean isExcludedClass(final String className) {
		final String packageName = extractPackageName(className);
		if (packageName.isEmpty()) {
			return false;
		}
		if (exactPackageExclusions.contains(packageName)) {
			return true;
		}
		for (final String prefixExclusion : prefixPackageExclusions) {
			if (matchesPrefixExclusion(packageName, prefixExclusion)) {
				return true;
			}
		}
		return false;
	}

	private static boolean matchesPrefixExclusion(final String packageName, final String prefixExclusion) {
		if (packageName.startsWith(prefixExclusion)) {
			return true;
		}
		if (!prefixExclusion.endsWith(".")) {
			return false;
		}
		return packageName.equals(prefixExclusion.substring(0, prefixExclusion.length() - 1));
	}

	private static String extractPackageName(final String className) {
		final int separatorIndex = className.lastIndexOf('.');
		if (separatorIndex < 0) {
			return "";
		}
		return className.substring(0, separatorIndex);
	}

	private static List<String> createDefaultPrefixExclusions() {
		final List<String> exclusions = new ArrayList<String>();
		exclusions.add("java.");
		exclusions.add("javax.");
		exclusions.add("sun.");
		exclusions.add("com.sun.");
		exclusions.add("jdk.");
		exclusions.add("org.");
		exclusions.add("io.");
		return exclusions;
	}
}